name: wbrumbrum-env

channels:
  - conda-forge

dependencies:
  - python=3.12.3
  - jupyter=1.0.0
  - jupyterlab=4.0.11
  - matplotlib=3.8.4
  - numpy=1.26.4
  - scipy=1.13.1
  - pandas=2.2.2
  - control=0.10.0
